# Generated by Django 2.0.2 on 2018-04-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Answer',
        ),
    ]
